<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
 <%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Admin Panel</title>
 <link rel="stylesheet" href="adminPanel.css" />
</head>
<body>
	<header class="header" role="banner">
   <div class="header-left">
    <img alt="Logo placeholder with letter X" height="32" src="https://storage.googleapis.com/a1aa/image/1053bc05-9f82-4425-32d7-90488d4e8bb9.jpg" width="32"/>
    <span>AdminPanel</span>
   </div>
   <div class="header-right">
    <span>Admin</span> 
    <a class="logout" href="#" role="link" tabindex="0">Logout</a>
   </div>
  </header>
  <div class="container">
   <nav aria-label="Main navigation" class="sidebar" role="navigation">
    <a href="#" tabindex="0"> Dashboard</a>
    <a href="#" tabindex="0"> Manage Videos </a>
    <a aria-current="page" class="active" href="GetAllAds" tabindex="0"> Manage Ads</a>
    <a href="#" tabindex="0"> Users</a>
    <a href="#" tabindex="0"> Reports</a>
   </nav>

   <main class="content" role="main">
    <h2> Manage Advertisements </h2>
    <a href="createAd.jsp" class="btn-create-ad" role="button" tabindex="0">Create Advertisement</a>

    <section aria-labelledby="advertisement-list-title" class="card">
     <h3 id="advertisement-list-title" style="font-size: 15px; font-weight: 700; margin-bottom: 12px; color: #111827;">Advertisement List </h3>
     <table aria-describedby="advertisement-list-title" role="table" id="ads-table">
      <thead>
       <tr>
        <th scope="col">ID</th>
        <th scope="col">Title</th>
        <th scope="col">Media_url</th>
        <th scope="col">Position</th>
        <th scope="col">Start_date</th> 
        <th scope="col">End_date</th> 
        <th scope="col">Status</th>
        <th scope="col">Views </th>  
        <th scope="col">Actions</th>
       </tr>
      </thead>
      <tbody>
      <c:forEach var="ad" items="${adsDetails}">
       <tr>
        <td>${ad.id}</td>
        <td>${ad.title} </td>
        <td>${ad.media_url}</td>
        <td>${ad.position}</td>
        <td>${ad.start_date}</td>
        <td>${ad.end_date}</td>
        <td><span aria-label="Active status" class="status-active">${ad.status} </span></td>
        <td>0</td>
        <td class="actions"><a class="edit" href="updateAd.jsp?id=${ad.id}&title=${ad.title}&media_url=${ad.media_url}&position=${ad.position}&start_date=${ad.start_date}&end_date=${ad.end_date}&status=${ad.status}" tabindex="0"> Edit </a>
            <a class="delete" href="adDeleteServlet?id=${ad.id}" onclick="return confirmDelete();" tabindex="0">Delete  </a>
        </td>
       </tr>
       </c:forEach>
      </tbody>
     </table>
    </section>
    <section aria-labelledby="advertisement-requests-title" class="card">
     <h3 id="advertisement-requests-title" style="font-size: 15px; font-weight: 700; margin-bottom: 12px; color: #111827;">
      Advertisement
      <a href="RequestsGetAll" class="request"> Requests</a>
     </h3>
     <table aria-describedby="advertisement-requests-title" role="table" id="requests-table">
      <thead>
       <tr>
        <th scope="col">ID</th>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Media URL</th>
        <th scope="col">Contact</th>
        <th scope="col">User</th>
       </tr>
      </thead>
      <tbody>
       <c:forEach var="requestsDetails" items="${allRequests}">
       <tr>
        <td>${requestsDetails.id}</td>
        <td>${requestsDetails.title}</td>
        <td>${requestsDetails.description}</td>
        <td>${requestsDetails.mediaURL}</td>
        <td>${requestsDetails.contact}</td>
        <td>${requestsDetails.userId}</td>
       </tr>
       </c:forEach>
      </tbody>
     </table>
    </section>

    <section aria-labelledby="analytics-title" class="card">
     <h3 id="analytics-title" style="font-size: 15px; font-weight: 700; margin-bottom: 16px; color: #111827;">
      Analytics - Most Viewed Active Ads
     </h3>
     <div class="analytics-chart-container" role="img" aria-label="Bar chart showing views count on y axis and ad IDs on x axis">
      <div class="y-axis" aria-hidden="true">
       <span>1,400</span>
       <span>1,100</span>
       <span>800</span>
       <span>500</span>
       <span>200</span>
       <span>0</span>
      </div>
      <div class="analytics-chart" id="analytics-chart">
       <!-- Bars generated by JS -->
      </div>
     </div>
    </section>
   </main>
  </div>
  
  <script src="analytics.js"></script>
  <script>
	  function confirmDelete() {
	    return confirm("Are you sure you want to delete this advertisement?");
	  }
  </script>

  
</body>
</html>